name: Run Script 12pm

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests rich
    - name: Run now
      run: |
        python auto-lingo.py
